Km 81 connect gcloud db prisma
fullstacksmart/next-kara pull request #47
Opened 2021-04-17 17:37 UTC by Maeaex

Hinzufügen .env in Prisma Folder mit Connection String (siehe Email mit .env File an euch). 

Alex Migration in die DB hat über Prisma tadellos geklappt.

![image](https://user-images.githubusercontent.com/43932887/115121600-dff0e180-9fb3-11eb-9249-3f03be303c98.png)

2021-04-24 14:52 UTC, beckertobias approved these changes
Looks good to me. I didn't test it but I trust you that it's working.
I already had a look at Alex' PR before.
We just have to pay attention: If we merge this PR, we shouldn't merge Alex' PR because this one already includes his commits.

2021-04-30 14:53 UTC, atsteinberg requested changes
Hey Max. Sorry, this would have been easier without KM-91 mixed in. So, could you just quickly say which changes you made (or even better: if it was not a lot: do them again in a clean branch from current main)? That would be awesome!

2021-04-30 14:53 UTC, atsteinberg commented on .gitignore
> +prisma/.env
there is no such file. What is this supposed to achieve?

2021-04-30 14:53 UTC, atsteinberg commented on .gitignore
> +app.yaml
there is no such file. What is this supposed to achieve?

2021-04-30 14:53 UTC, atsteinberg commented on .gitignore
> +mythical-module-308515-8f036fb55006.json
there is no such file. What is this supposed to achieve?

2021-04-30 14:53 UTC, atsteinberg commented on apollo/helpers.ts
> +// return models.Talent.findMany().map((talent: User) => talent.id);
please delete comment

2021-04-30 14:53 UTC, atsteinberg commented on pages/talents/[id]/index.tsx
> +const GET_ALL_TALENTS = gql`
please remove code that is for testing purposes before merging to main

2021-04-30 14:53 UTC, atsteinberg commented on pages/talents/[id]/index.tsx
> +  const { data: talentIds, loading: idLoading } = useQuery(GET_ALL_TALENTS);
please remove code that is for testing purposes before merging to main

2021-04-30 14:53 UTC, atsteinberg commented on pages/talents/[id]/index.tsx
> +  console.log(talentIds);
please remove code that is for testing purposes before merging to main

2021-04-30 14:53 UTC, atsteinberg commented on pages/talents/[id]/index.tsx
> -ProfilePage.getInitialProps = async () => ({
we might need this. @beckertobias ?

2021-04-30 14:55 UTC, atsteinberg commented on .gitignore
> +mythical-module-308515-8f036fb55006.json
or is this generated once you run something?

2021-04-30 15:00 UTC, atsteinberg commented on .gitignore
> +prisma/.env
this is already caught by line 30

2021-04-30 15:31 UTC, atsteinberg commented
I'm closing this mr, because it is already included in merged KM-91.

2021-04-30 15:31 UTC, closed without merging